# Long Tutorial

```{r 001-comment-1, eval = FALSE}
# http://www.r-programming.org/papers
```

```{r 001-symbols}
symbols <- basic_symbols()
```

## Quantstrat

```{r 001-getSymbols}
getSymbols(Symbols = symbols,
           src = "yahoo",
           index.class = "POSIXct",
           from = start_date,
           to = end_date,
           adjust = adjustment)
```

```{r 001-stock}
stock(symbols, currency = "USD", multiplier = 1)
```

```{r 001-init}
portfolio.st <- "qsFaber"
account.st <- "qsFaber"
strategy.st <- "qsFaber"
```

```{r 001-rm-strat}
rm.strat(portfolio.st)
rm.strat(account.st)
```

```{r 001-init-portf}
initPortf(name = portfolio.st,
          symbols = symbols,
          initDate = init_date)
```

```{r 001-init-acct}
initAcct(name = account.st,
         portfolios = portfolio.st,
         initDate = init_date,
         initEq = init_equity)
```

```{r 001-init-orders}
initOrders(portfolio = portfolio.st,
           symbols = symbols,
           initDate = init_date)
```

```{r 001-strategy}
strategy(strategy.st, store = TRUE)
```

### Add Indicator

```{r 001-add-indicator}
add.indicator(strategy = strategy.st,
              name = "SMA",
              arguments = list(x = quote(Cl(mktdata)),
                               n = 20),
              label = "SMA20")
```

### Add Signal

```{r 001-add-signal}
add.signal(strategy = strategy.st,
           name="sigCrossover",
           arguments = list(columns = c("Close", "SMA20"),
                            relationship = "gte"),
           label = "Cl.gte.SMA20")

add.signal(strategy = strategy.st,
           name="sigCrossover",
           arguments = list(columns = c("Close", "SMA20"),
                            relationship = "lt"),
           label = "Cl.lt.SMA20")
```

### Add Rule

```{r 001-add-rule}
add.rule(strategy = strategy.st,
         name = "ruleSignal",
         arguments = list(sigcol = "Cl.gte.SMA20",
                          sigval = TRUE,
                          orderqty = 100,
                          ordertype = "market",
                          orderside = "long"),
         type = "enter",
         label = "Long.Entry")

add.rule(strategy.st,
         name = "ruleSignal",
         arguments = list(sigcol = "Cl.lt.SMA20",
                          sigval = TRUE,
                          orderqty = "all",
                          ordertype = "market",
                          orderside = "long"),
         type = "exit",
         label = "Long.Exit")
```

### Apply Strategy

```{r 001-applyStrategy, results = "hide"}
applyStrategy(strategy.st, portfolio.st, debug = TRUE)
```

```{r 001-checkBlotterUpdate}
checkBlotterUpdate(portfolio.st, account.st, verbose = TRUE)
```

### Update Objects

```{r 001-update}
# Update Objects
updatePortf(Portfolio = portfolio.st)
updateAcct(name = account.st)
updateEndEq(Account = account.st)
```

### Equity Curve
```{r 001-equity-curve}
a <- getAccount(account.st)
equity <- a$summary$End.Eq
plot(equity, main = "Consolidated Equity Curve")
```

### Plot Performance

```{r 001-plot-performance}
for(symbol in symbols) {
    chart.Posn(strategy.st, Symbol = symbol, 
               TA = "add_SMA(n = 20, col = 4, on = 1, lwd = 2)")
}
```

### Trade Stats

```{r 001-trade-stats}
trade_stats <- t(tradeStats(strategy.st))
as.data.frame(trade_stats)
```

### Order Book

```{r 001-order-book, results = "asis"}
ob <- getOrderBook(strategy.st)
ob$qsFaber$SPY[,1:5]
ob$qsFaber$SPY[,6:11]
```

### Per Trade Statistics

```{r 001-per-trade-stats}
perTradeStats(strategy.st)
```

### MAE

```{r 001-mae}
for(symbol in symbols) {
    chart.ME(Portfolio = portfolio.st, Symbol = symbol, type = "MAE", 
             scale = "percent")
}
```

### MFE

```{r 001-mfe}
for(symbol in symbols) {
    chart.ME(Portfolio = portfolio.st, Symbol = symbol, type = "MFE", 
             scale = "percent")
}
```

### Get Account

```{r 001-get-account}
a <- getAccount(strategy.st)
last(a$summary, 5)
```

### Account Summary

```{r 001-account-summary}
xyplot(a$summary, type = "h", col = 4)
```

### Strategy Performance

```{r 001-strat-perf}
ret <- Return.calculate(equity, method = "log")
charts.PerformanceSummary(ret, colorset = bluefocus, 
                          main = "Strategy Performance")
```

### Cumulative Returns

```{r 001-cumulative-returns}
rets.multi <- PortfReturns(account.st)
colnames(rets.multi) <- symbols
rets.multi <- na.omit(cbind(rets.multi, Return.calculate(a$summary$End.Eq)))
names(rets.multi)[length(names(rets.multi))] <- "TOTAL"
rets.multi <- rets.multi[,c("TOTAL", symbols)]
round(tail(rets.multi, 5), 6)
chart.CumReturns(rets.multi, colorset = rich10equal, legend.loc = "topleft", 
                 main = "Strategy Cumulative Returns")
```

```{r 001-returns-boxplot}
chart.Boxplot(rets.multi, main = "Strategy Returns", colorset = rich10equal)
```

### Annualized Returns

```{r 001-annualized-returns}
(ar.tab <- table.AnnualizedReturns(rets.multi))
max.risk <- max(ar.tab["Annualized Std Dev",])
min.risk <- min(ar.tab["Annualized Std Dev",])
max.return <- max(ar.tab["Annualized Return",])
min.return <- min(ar.tab["Annualized Return",])
chart.RiskReturnScatter(rets.multi,
                        main = "Strategy Performance", colorset = rich10equal,
                        xlim = c(min.risk, max.risk), ylim = c(min.return, max.return))
```

### Chart Series

```{r 002-chart-series}
chart_Series(SPY["2009"], TA = "add_BBands(lwd = 2)", name = "SPY")
```
