# Basic Strategy II {#basic-strategy-ii}

In [Basic Strategy](#basic-strategy) we did a simple strategy of buying n number of shares on a fixed moving average. 

In this slightly modified example we'll pass the SMA `n` parameter to `applyStrategy()`. 

```{r 3-rm-strat}
rm.strat(portfolio.st)
rm.strat(account.st)
```

```{r 3-init-portf}
initPortf(name = portfolio.st,
          symbols = symbols,
          initDate = init_date)
```

```{r 3-init-acct}
initAcct(name = account.st,
         portfolios = portfolio.st,
         initDate = init_date,
         initEq = init_equity)
```

```{r 3-init-orders}
initOrders(portfolio = portfolio.st,
           symbols = symbols,
           initDate = init_date)
```

```{r 3-strategy}
strategy(strategy.st, store = TRUE)
```

```{r 3-add-indicators}
add.indicator(strategy = strategy.st,
              name = "SMA",
              arguments = list(x = quote(Cl(mktdata))),
              label = "SMA20")
```

Notice in `add.indicator` we did not supply the `n` parameter as we did before. 

```{r 3-add-signals}
add.signal(strategy = strategy.st,
           name="sigCrossover",
           arguments = list(columns = c("Close", "SMA20"),
                            relationship = "gte"),
           label = "Cl.gte.SMA20")

add.signal(strategy = strategy.st,
           name="sigCrossover",
           arguments = list(columns = c("Close", "SMA20"),
                            relationship = "lt"),
           label = "Cl.lt.SMA20")
```

```{r 3-add-rules}
# BTO when Cl crosses above SMA(20)
add.rule(strategy = strategy.st,
         name = "ruleSignal",
         arguments = list(sigcol = "Cl.gte.SMA20",
                          sigval = TRUE,
                          orderqty = 100,
                          ordertype = "market",
                          orderside = "long"),
         type = "enter",
         label = "BTO")

# STC when Cl crosses under SMA(20)
add.rule(strategy.st,
         name = "ruleSignal",
         arguments = list(sigcol = "Cl.lt.SMA20",
                          sigval = TRUE,
                          orderqty = "all",
                          ordertype = "market",
                          orderside = "long"),
         type = "exit",
         label = "STC")
```

```{r 3-apply-strategy, results = "hide"}
# Results hidden to save space
applyStrategy(strategy.st,
              portfolios = portfolio.st,
              parameters = list(n = 20))
```

```{r 3-update}
updatePortf(portfolio.st)
updateAcct(account.st)
updateEndEq(account.st)
```

```{r 3-checkBlotterUpdate}
checkBlotterUpdate(portfolio.st, account.st, verbose = TRUE)
```

```{r 3-equity-curve}
a <- getAccount(account.st)
equity <- a$summary$End.Eq
plot(equity, main = "Consolidated Equity Curve")
```
