# Warnings and Errors

It is very frustrating to hammer out tons of code only to find an error on execution. Often the errors and warnings do not provide much input - especially for beginners. 

Messages below are not intended to state specifically where the issue may be. Hopefully they will point you in the right direction.

## Must use auto.assign=TRUE for multiple Symbols requests

> Error in getSymbols(Symbols = symbols, reload.Symbols = FALSE, verbose = FALSE,  : 
  must use auto.assign=TRUE for multiple Symbols requests

You intentionally set `auto.assign` to false in `getSymbols()` while also calling multiple symbols. If you are loading `getSymbols()` with multiple symbols, set `auto.assign = FALSE` or remove the parameter as FALSE is the default setting.

See `?getSymbols` for more information on `auto.assign`.

## Missing in call to function add.distribution

> Error in must.have.args(match.call(), c("strategy", "paramset.label",  : 
>  label: argument(s) missing in call to function add.distribution

You're missing a label argument in your `add.distribution` call. 
