--- 
title: "Backtesting Trading Strategies in R"
author: "Tim Trice"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
output: 
    bookdown::gitbook:
        lib_dir: assets
        config: 
            toolbar:
                position: static
        highlight: default
        split_by: section
    bookdown::pdf_book:
        keep_tex: yes
    bookdown::html_chapters:
        css: toc.css
documentclass: book
description: "Backtesting strategies with R"
site: bookdown::bookdown_site
---

```{r index-comments, eval = FALSE, echo = FALSE}
# Click "Knit" button above to view sample
# Live serve:
#       bookdown:::serve_book()
# Produce gitbook output: 
#       bookdown:;render_book("index.Rmd", "bookdown::gitbook")
# To produce PDF output: 
#       bookdown::render_book("index.Rmd", "bookdown::pdf_book")
# Preview a chapter:
#       bookdown::preview_chapter("file.Rmd")
```

# Introduction

  * Packages required
  
    + blotter
    
    + PerformanceAnalytics
    
    + PortfolioAnalytics
    
    + quantmod
    
    + quantstrat
    
    + tidyquant
    
    + TTR
  
  * Purpose of each package and their dependencies.

  * sessionInfo()

# Gathering Data

  * Finding symbols
  
  * Getting OHLC data
  
    + Yahoo
    
    + Google
    
    + FRED

## Analyzing Data

  + tidyquant
  
  + Converting time series data
  
  + plotting time series data

## Technical Indicators

  * Moving Averages
  
  * Bollinger Bands
  
  * RSI

## Trading Signals

## Position Rules

## Preliminary Analysis

  * Applying a strategy
  
  * Plotting trades
  
  * trade statistics
  
  * account summary

## Detailed Analysis

## Overfitting

## Walk Forward Analysis

## Monte Carlo Analysis

## Documenting Your Strategy

## Paper Trading Your Strategy

## Let's Do It Live!

  + monitoring your trading activity

Notes:

  1. Maybe a demonstration using Think or Swim

## About

## Index
