# Trailing Stops {#trailing-stops}

```{block type = "strategy"}
If Signal Line crosses above 0:
    BTO
Else If Signal Line crosses below 0:
    STC
```

```{r trailing-stop-strategy-vars}
trailingStopPercent <- 0.07
trade_size <- init_equity/length(symbols)
```

```{r trailing-stop-create-objects}
portfolio.st <- "Quantstrat"
account.st <- "Strategies"
strategy.st <- "MACD.TS"
```

```{r trailing-stop-rm-strat}
rm.strat(portfolio.st)
rm.strat(account.st)
```

```{r trailing-stop-init-portf}
initPortf(name = portfolio.st,
          symbols = symbols,
          initDate = init_date)
```

```{r trailing-stop-init-acct}
initAcct(name = account.st,
         portfolios = portfolio.st,
         initDate = init_date,
         initEq = init_equity)
```

```{r trailing-stop-init-orders}
initOrders(portfolio = portfolio.st,
           symbols = symbols,
           initDate = init_date)
```

```{r trailing-stop-strategy}
strategy(strategy.st, store = TRUE)
```

## osFixedDollar

quantstratIII pg. 11/66

$$ \text{orderqty} = \frac{\text{trade_size}}{\text{Cl}} $$

```{r}
osFixedDollar <- function(timestamp, orderqty, portfolio, symbol, ruletype, ...) {
    if(!exists("trade_size")) stop("You must set trade_size")
    ClosePrice <- as.numeric(Cl(mktdata[timestamp,]))
    orderqty <- round(trade_size/ClosePrice,-2)
    return(orderqty)
}
```

## Add Indicators

```{r trailing-stop-add-indicators}
add.indicator(strategy = strategy.st,
              name = "MACD",
              arguments = list(x = quote(Cl(mktdata))),
              label = "osc")
```

## Add Signals

```{r trailing-stop-add-signals}
add.signal(strategy = strategy.st,
           name="sigThreshold",
           arguments = list(column ="signal.osc", 
                            relationshipo = "gt", 
                            threshold = 0, 
                            cross = TRUE), 
           label = "signal.gt.zero")

add.signal(strategy = strategy.st,
           name="sigThreshold",
           arguments = list(column = "signal.osc", 
                            relationship = "lt", 
                            threshold = 0, 
                            cross = TRUE), 
           label = "signal.lt.zero")
```

## Add Rules

```{r trailing-stop-add-rule}
add.rule(strategy = strategy.st,
         name = "ruleSignal",
         arguments = list(sigcol = "signal.gt.zero",
                          sigval = TRUE,
                          orderqty = 100,
                          orderside = "long",
                          ordertype = "market",
                          osFUN = "osFixedDollar", 
                          orderset = "ocolong"),
         type = "enter",
         label = "LE")

add.rule(strategy = strategy.st, 
         name = "ruleSignal", 
         arguments = list(sigcol = "signal.lt.zero", 
                          sigval = TRUE, 
                          replace = TRUE, 
                          orderside = "long", 
                          ordertype = "market", 
                          orderqty = "all", 
                          orderset = "ocolong"), 
         type = "exit", 
         label = "LX")

add.rule(strategy = strategy.st, 
         name = "ruleSignal", 
         arguments = list(sigcol = "signal.gt.zero", 
                          sigval = TRUE, 
                          replace = FALSE, 
                          orderside = "long", 
                          ordertype = "stoptrailing", 
                          tmult = TRUE, 
                          threshold = quote(trailingStopPercent), 
                          orderqty = "all", 
                          orderset = "ocolong"), 
         type = "chain", 
         parent = "LE", 
         label = "StopTrailingLong", 
         enabled = FALSE)
```

## Enable Rules

```{r trailing-stop-enable-rules}
enable.rule(strategy.st, type = "chain", label = "StopTrailingLong")
```

## Save Strategy

```{r trailing-stop-save-strategy}
cwd <- getwd()
setwd("./_data/")
save.strategy(strategy.st)
setwd(cwd)
```
